bananagrams/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView
from game.forms import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('game/', include('game.urls')),
    path('', include('game.urls')),
    path('register/', SignUpView.as_view(), name='register'),
]

game/urls.py
from django.urls import include, path, re_path

from . import views

app_name = 'game'
urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('newgame/', views.createNewGame, name='newgame'),
    path('join/<str:urlKey>/', views.joinGame, name='join'),
    path('events/<int:gameId>/', views.getGameEvents, name='events'),
    path('update/<int:gameId>/', views.updatePlayerState, name='update'),
    path('start/<int:gameId>/', views.startGame, name='start'),
]

game/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from .utils import TILE_COUNT, getTilesAsList, generateUrlKey

# Create your models here.
class Game(models.Model):
    game_name = models.CharField(default='Bananagrams', max_length=30)
    num_players = models.PositiveIntegerField(validators=[MinValueValidator(2), MaxValueValidator(5)])
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(blank=True, null=True)
    remaining_tiles = models.CharField(max_length=TILE_COUNT, default=''.join(getTilesAsList()))
    url_key = models.CharField(max_length=100, default=generateUrlKey())
    active = models.BooleanField(default=False)
    def __str__(self):
        return "%d %s (%d)" % (self.pk, self.game_name, self.num_players)

class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete = models.CASCADE, blank=True)
    active = models.BooleanField(default=False)
    rack = models.CharField(max_length=TILE_COUNT, blank=True)
    grid = models.TextField(blank=True)
    is_host = models.BooleanField(default=False)
    def __str__(self):
        return "%s %s" % (self.user, self.game.game_name)

class EventTypes:
    EVENT_CREATE = 'CREATE'
    EVENT_START = 'START'
    EVENT_JOIN = 'JOIN'
    EVENT_PEEL = 'PEEL'
    EVENT_DUMP = 'DUMP'
    EVENT_BANANAS = 'BANANAS'
    EVENT_WIN = 'WIN'
    EVENT_ROTTEN = 'ROTTEN'
    EVENT_FULL = 'FULL'

class Event(models.Model):
    EVENT_TYPES = (
        (EventTypes.EVENT_CREATE, 'CREATE'),
        (EventTypes.EVENT_START, 'START'),
        (EventTypes.EVENT_JOIN, 'JOIN'),
        (EventTypes.EVENT_PEEL, 'PEEL'),
        (EventTypes.EVENT_DUMP, 'DUMP'),
        (EventTypes.EVENT_BANANAS, 'BANANAS'),
        (EventTypes.EVENT_WIN, 'WIN'),
        (EventTypes.EVENT_ROTTEN, 'ROTTEN'),
        (EventTypes.EVENT_FULL, 'FULL')
    )
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    event_info = models.TextField()
    event_type = models.CharField(max_length=10, choices=EVENT_TYPES, default=EventTypes.EVENT_CREATE)
    event_time = models.TimeField(auto_now_add=True)

game/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/register.html'

class CreateGameForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'createGameForm'
        self.helper.form_method = 'post'
        self.helper.form_action = "game:newgame"

        self.helper.add_input(Submit('submit', 'Create Game'))

    game_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'A Bananagrams Game'}))
    player_count = forms.ChoiceField(widget=forms.Select, choices=[(i, i) for i in range(2, 9)])

game/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse, JsonResponse
from .models import Player, Game, Event, EventTypes
from django.shortcuts import render
from .utils import *
from .forms import CreateGameForm
from datetime import datetime
from django.contrib.auth.decorators import login_required
from .signals import event_signal

def home(request):
    if request.user.is_authenticated:
        return redirect('game:index')
    else:
        return render(request, 'index.html')

@login_required()
def index(request):
    try:
        activePlayer = Player.objects.get(user=request.user, active=True)
        activeGame = activePlayer.game
        context = {
            'player': activePlayer,
            'game': activeGame
        }
        return render(request, 'index.html', context)
    except Exception as e:
        print(e)
        return render(request, 'index.html', {'create_game_form': CreateGameForm()})

@login_required
def createNewGame(request):
    gameName = request.POST['game_name']
    numPlayers = request.POST['player_count']
    newGame = Game(game_name=gameName, num_players=numPlayers, active=True)
    newGame.save()
    host = Player(user=request.user, game=newGame, active=True, is_host=True)
    host.save()
    event_signal.send(sender=None, user=request.user, game=newGame, eventType=EventTypes.EVENT_CREATE)
    return redirect('game:index')

@login_required
def checkGameAvailabilityByUrl(request, urlKey):
    game = Game.objects.get(url_key=url_key, active=True)
    if game:
        return HttpResponse("CAN JOIN GAME" if numPlayersInGame(game) < game.num_players else "GAME IS FULL")
    else:
        return HttpResponse("GAME DOES NOT EXIST")

def numPlayersInGame(game):
    presentPlayers = Player.objects.all().filter(game=game, active=True)
    return len(presentPlayers)

@login_required
def joinGame(request, urlKey):
    game = Game.objects.get(url_key=urlKey, active=True)
    existingPlayers = numPlayersInGame(game)
    if existingPlayers < game.num_players:
        guest, created = Player.objects.get_or_create(user=request.user, game=game, active=True, is_host=False)
        if created: guest.save()
        event_signal.send(sender=None, user=request.user, game=game, eventType=EventTypes.EVENT_JOIN)
        if existingPlayers == game.num_players - 1:
            event_signal.send(sender=None, user=request.user, game=game, eventType=EventTypes.EVENT_FULL)
        return redirect('game:index')
    else:
        return HttpResponse("GAME IS FULL")

@login_required
def startGame(request, gameId):
    game = Game.objects.get(pk=gameId)
    # check that there are enough players
    players = Player.objects.all().filter(game=game, active=True)
    if (len(players) != game.num_players):
        return HttpResponse("NOT ENOUGH PLAYERS")

    startTileCount = getStartTileCount(game.num_players)
    distributeTiles(startTileCount, game)

    event_signal.send(sender=None, user=request.user, game=game, eventType=EventTypes.EVENT_START)
    return HttpResponse("STARTED")

def distributeTiles(numTiles, game):
    players = Player.objects.select_for_update().all().filter(game=game, active=True)
    tiles = list(game.remaining_tiles)

    for player in players:
        player.rack += ''.join(tiles[:numTiles])
        tiles = tiles[numTiles:]
        player.save()
    game.remaining_tiles = ''.join(tiles)
    game.save()

# Player has finished their grid and clicks PEEL
# When a player peels, ALL players must take one tile
@login_required
def peel(request, gameId):
    game = Game.objects.select_for_update().get(pk=gameId)
    peeler = Player.objects.select_for_update().get(user=request.user, game=game)
    newGrid = request.POST['grid']
    if validatePeel(peeler.grid, peeler.rack, newGrid):
        peeler.grid = newGrid
        peeler.rack = ""
        peeler.save()
        distributeTiles(1, game)
        event_signal.send(sender=None, user=request.user, game=game, eventType=EventTypes.EVENT_PEEL)
    else:
        return HttpResponse("Invalid Move")

# When a player dumps, they put one tile back and take 3 more (if available)
@login_required
def dump(request, gameId, toDump):
    game = Game.objects.select_for_update().get(pk=gameId)
    tiles = list(game.remaining_tiles)
    if len(tiles) == 0:
        return HttpResponse('Cannot dump')
    dumper = Player.objects.select_for_update().get(user=request.user, game=game)
    rack = list(dumper.rack)
    rack.remove(toDump)
    
    for i in range(min(3, len(tiles))):
        rack.append(tiles.pop(0))
    tiles.append(toDump)
    game.remaining_tiles = tiles
    game.save()
    dumper.rack = ''.join(rack)
    dumper.save()

    event_signal.send(sender=None, user=request.user, game=game, eventType=EventTypes.EVENT_DUMP)
    return HttpResponse('Dumped')

# poll for game events
@login_required
def getGameEvents(request, gameId):
    game = Game.objects.get(pk=gameId)
    event = Event.objects.all().filter(game=game).order_by('-event_time')[0]

    return JsonResponse({
        'tilesLeft': len(game.remaining_tiles),
        'event': {
            'time': event.event_time,
            'info': event.event_info,
            'event_type': event.event_type
        }
    })

# update player state if an event requires it (peel, bananas, dump)
@login_required
def updatePlayerState(request, gameId):
    game = Game.objects.get(pk=gameId)
    player = Player.objects.get(user=request.user, game=game)
    return JsonResponse({
        'rack': player.rack,
        'active': player.active
    })

# No more tiles to distribute, and one player finishing up = Bananas
@login_required
def bananas(request, gameId):
    game = Game.objects.select_for_update().get(pk=gameId)
    caller = Player.objects.select_for_update().get(user=request.user, game=game)
    newGrid = request.POST['grid']
    event_signal.send(sender=None, user=request.user, game=game, eventType=EventTypes.EVENT_BANANAS)

    if validateBananas(newGrid):
        game.end_time = datetime.now()
        game.save()
        event_signal.send(sender=None, user=request.user, game=game, eventType=EventTypes.EVENT_WIN)
        return HttpResponse("You win!")
    else:
        return HttpResponse("Rotten Banana")

game/templates/active_game.html
<div class='row'>
  <div class="mr-auto">
    Share this lobby URL for others to join (click to copy):
    <a href="#" id='joinlink'>{{ request.get_host }}{% url 'game:join' game.url_key %}</a>
  </div>
  <div id="copyAlert" class="ml-auto alert alert-success alert-dismissible fade show" role="alert" style="display: none">
    Link copied.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>

<div class='row'>
  <div class='col-9'>
    <div class='container'>
      <canvas id='grid'></canvas>
      <div class='row'></div>
    </div>
    
  </div>
  <div class='col-3' id='event-panel'>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">Game Progress</h4>
      </div>
      <div class="panel-body" id='event-container'></div>
    </div>
    <div>
      {% if player.is_host %}
      <button class='btn btn-primary' id='startBtn' disabled>Start Game</button>
      {% endif %}

      <button class='btn btn-warning' id='peelBtn' disabled>Peel</button>
    </div>
  </div>
</div>

{% block extra_js %}
{% load static %}
  <script src="{% static "js/game.js" %}"></script>
  <script>
  $(function() {
    var eventUrl = "{% url 'game:events' game.pk %}";
    var playerStateUrl = "{% url 'game:update' game.pk %}"
    var startUrl = "{% url 'game:start' game.pk %}"
    var interval = pollForEvents(eventUrl, playerStateUrl);

    $('#joinlink').click(function() {
      var joinlink = $(this).text();
      copyToClipboard(joinlink);
      $('#copyAlert').show();
    });

    $('#startBtn').click(function() {
      $.get(startUrl, function(result) {
        if (result == 'STARTED') {
          console.log("Started game");
        } else {
          console.err(result);
        }
      });
    });
  });
  </script>
{% endblock %}

{% block extra_css %}
{% load static %}
  <link rel="stylesheet" href="{% static "css/game.css" %}">
{% endblock %}

game/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
{% block extra_css %}
{% endblock %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  
</head>
<body>
{% if user.is_authenticated %}
  {% include "navbar.html" %}
{% endif %}

{% block content %}
{% endblock %}

{% block extra_js %}
{% endblock %}
</body>
</html>

game/templates/index.html
<!-- templates/index.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <!-- Page content -->
  <div class="container-fluid">
    {% if game %}
      {% include "active_game.html" %}
    {% else %}
      Hi {{ user.username }}! You aren't playing a game right now. Would you like to create one?
      {% load crispy_forms_tags %}
      {% crispy create_game_form create_game_form.helper %}
    {% endif %}
  </div>
  <!-- /#page-content-wrapper -->
{% else %}
  <p>You are not logged in</p>
  <a class="btn btn-primary" href="{% url 'game:login' %}">Log In</a>
  <a class="btn btn-info" href="{% url 'register' %}">Sign up</a>
{% endif %}
{% endblock %}

game/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Banana Grams</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li id="navbarCurrentGame" class="nav-item">
        <a class="nav-link" href="{% url 'game:index' %}">Current Game</a>
      </li>
      <li id="navbarHistory" class="nav-item">
        <a class="nav-link" href="#">History</a>
      </li>
      <li id="navbarSpectate" class="nav-item">
        <a class="nav-link" href="#">Spectate</a>
      </li>
      
    </ul>
    
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Profile</a>
          <a class="dropdown-item" href="#">Friends</a>
          <a class="dropdown-item" href="{% url 'game:logout' %}" onclick="confirm('Are you sure you want to stop playing?');">Log Out</a>
        </div>
      </li>
    </ul>

  </div>
</nav>